### ISSUE TITLE
Cannot input 0.001 into job amount

### ISSUE THREAD

**Issue by madvas** [district0x/ethlance#392]
neither 0.0.. or 0,0... works, both comma and dot should work equally. 

![image](https://github.com/district0x/ethlance/assets/3857155/bdc06458-72ce-43e6-b335-f636c7217817)

**Comment by madis** [comment]
In this case is so due to how the numeric input with `step`  parameter works.
Any fraction with the precision up to the decimal places set by `step` can be done by using the up and down arrows or entering a 3 digit precision and then changing the value. E.g. you want `0.051` so you first enter `0.151` and then replace 

https://github.com/district0x/ethlance/assets/674621/c39bd273-a5b1-47f5-bd98-1dc365be8d7f

**Comment by madvas** [comment]
![image](https://github.com/district0x/ethlance/assets/3857155/42d89c56-5216-41c0-85e3-9fec3598c2f8)
This input needs to be fixed as well

**Comment by madvas** [comment]
Dot "." still doesn't work, only comma "," works, like 0,001. And 0.001 doesn't work

**Comment by madvas** [comment]
Dot . is still not working for inputing decimal numbers

**Comment by madis** [comment]
> Dot "." still doesn't work, only comma "," works, like 0,001. And 0.001 doesn't work

The accepted decimal separator (`.` or `,`) the `<input type="number">` accepts depends on the locale set on your computer. For me it's the `.` (period) that works.

Also, on new invoice page in order to enter the amount, first a job needs to be selected from the drop-down

As a fix I disabled the inputs until the job gets chosen from the drop-down. 
Please let me know if this is an acceptable solution?

https://github.com/district0x/ethlance/assets/674621/e2afa2e4-6f1e-4aec-bd92-f0a656f28909

**Comment by madvas** [comment]
No, there's no reason we should enforce order of inputs on user. But this doesn't work for me on all number inputs. I'm using english keyboard locale.
