### ISSUE TITLE
A system of penalties for freelancers and employers (or autodeleting of job offers)

### ISSUE THREAD

**Issue by blockchain-doppelganger** [district0x/ethlance#45]
employers can forget about their job post on Ethlance, and freelancers will continue to add offers that are an excessive waste of time and Ethers.

Or add some time restriction for employer's job proposals. after some time this post will be destroyed.

**Comment by benzap** [comment]
The ethlance 2.0 rework contains a server-side component, which will allow us to inform the employers when job proposals are being made.

Unfortunately, the current version of Ethlance is completely client-side, which is a marvel, but prevents us to inform employers through email, since that is something that is handled on the server-side.

We appreciate the feedback!
