### ISSUE TITLE
UI - Implement Arbiters Page

### ISSUE THREAD

**Issue by benzap** [district0x/ethlance#64]
# Desktop Preview
![](https://i.imgur.com/lNqGQQ7.png)

# Mobile Preview
![](https://i.imgur.com/8nFaKpT.png)

**Comment by madvas** [comment]
### Desktop
* Name should be larger font size and lower font weight
Impl:
![image](https://user-images.githubusercontent.com/3857155/66187036-0ab76580-e6ae-11e9-84b0-bf768df7eaec.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66187046-1014b000-e6ae-11e9-96dc-91ff53dd92e7.png)

* "Fixed price" shouldn't be there. There's no other option
Impl:
![image](https://user-images.githubusercontent.com/3857155/66187074-215dbc80-e6ae-11e9-9258-fef8f1432322.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66187089-2e7aab80-e6ae-11e9-8218-8e461c9df007.png)

* Tag are missing autocomplete. List of available tags are [here](https://github.com/district0x/ethlance/blob/master/resources/public/edn/skills.edn) 
Impl:
![image](https://user-images.githubusercontent.com/3857155/66187188-6c77cf80-e6ae-11e9-9857-e3e41e01c528.png)

* Profile picture should have more padding towards vertical sides. Actually, it looks like the whole app bar should be thicker.
Impl:
![image](https://user-images.githubusercontent.com/3857155/66187448-03448c00-e6af-11e9-8bc7-7e64dbac71e1.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66187487-135c6b80-e6af-11e9-8bb8-6a5c8c5cb986.png)

* Should say "Country" instead of "Select Country"
* Search input should have no placeholder
Impl:
![image](https://user-images.githubusercontent.com/3857155/66194068-f4b1a100-e6bd-11e9-97f7-dcac87d41351.png)

* Hover state styling is different than designs
Impl: 
![image](https://user-images.githubusercontent.com/3857155/66194276-5245ed80-e6be-11e9-8cb3-edf1dd1d276d.png)
Design:
![image](https://user-images.githubusercontent.com/3857155/66194299-5f62dc80-e6be-11e9-8565-2b49e08f42e3.png)

* Payment type is not needed for freelancers, as there'll be only fixed price
Impl:
![image](https://user-images.githubusercontent.com/3857155/66194358-7c97ab00-e6be-11e9-9e12-84a82e12d90d.png)

* Add Min. Price, Max. Price, Number of Feedbacks inputs for arbiters filtering
Impl:
![image](https://user-images.githubusercontent.com/3857155/66194416-99cc7980-e6be-11e9-9e9d-dc425eccb4e1.png)

**Comment by benzap** [comment]
Closing tickets that were refined, having a hard time keeping track
